### ISSUE TITLE
Add descriptions, readme, installation, and uninstallation directions.

### ISSUE THREAD

**Issue by androbtech** [tokaido/tokaidoapp#52]

**Comment by andrewhavens** [comment]
Yes, please. I think Tokaido is conflicting with an installation of Pow and Homebrew. Can you please provide un-install instructions?

**Comment by androbtech** [comment]
You can uninstall Tokaido by running:

```sudo sh path/to/Tokaido.app/Contents/Resources```

It seems you are having issues with booting applications with Tokaido. Will take a look (conflicts with Pow). You can select your app, click 'Open in Terminal', and run ```bundle exec rails server``` and browse the site as usual at http://localhost:3000

The reason there are conflicts with Pow is that both Pow and Tokaido fight for DNS resolution (Tokaido does it so that you can browse http://projname.tokaido)

Please open a ticket for a feature request (Tokaido's Ruby and it's Gems are isolated in case you need them)

Can you elaborate more the problem you are facing with Homebrew?
