### ISSUE TITLE
Rubymine and Tokaido

### ISSUE THREAD

**Issue by jamesrward** [tokaido/tokaidoapp#80]
Anyone have advice on using Rubymine with Tokaido?  How can I tell Rubymine to use the Tokaido SDK and Gems?  Currently if I open an existing Tokaido project in Rubymine it complains about missing gems.

**Comment by androbtech** [comment]
I haven't tried this but you probably need to tweak the Ruby and Gem configuration of your Rubymine project and set absolute paths appropriately.

In the case with latest Tokaido. The Ruby is at ```~/.tokaido/Rubies/2.1.5-p273/``` and the gems are at ```~/.tokaido/Gems/2.1.0/``` where ```~``` is your user directory.

**Comment by androbtech** [comment]
[Check here for picking an interpreter](https://www.jetbrains.com/ruby/help/configuring-local-ruby-interpreters.html)

**Comment by androbtech** [comment]
Can't find on the web a way to add the path where the Gems are. I did find a way to view the [Gem Environment](https://www.jetbrains.com/ruby/help/viewing-gem-environment.html). 

You need to dig in Rubymine and find a way to add the Gems path.

I'd also try setting the environment variables GEM_PATH and GEM_HOME to ```~/.tokaido/Gems/2.1.0/``` where ```~``` is your user directory.

**Comment by jamesrward** [comment]
As you suspected setting the interpreter is no problem now that I know the path but the Gems path is wrong and I don't see a way to set it manually.  Here's the errors I get after setting the interpreter:
```ruby
Error:Get available generators script executes with errors:
Error:/Users/James/.tokaido/Rubies/2.1.5-p273/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
Error:	from /Users/James/.tokaido/Rubies/2.1.5-p273/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```
I'll try the environment variables as suggested and see where that gets me.

**Comment by androbtech** [comment]
Please do and let me know.

**Comment by jamesrward** [comment]
I can set the environment variables for given execution profile (Development, Test) but not for the whole project.  It looks like this is an old issue:
http://stackoverflow.com/questions/25276281/can-environment-variables-be-provided-for-rubymine-tasks

I'm wondering if I can cheat and symlink the tokaido ruby and gemset into rvm so rubymine sees it.  Any thoughts?

**Comment by androbtech** [comment]
Please open a feature request, something like 'making it easier to integrate Tokaido to Rubymine' so I can work on this in the future.

You can pretty much do as you please. Tokaido is self-contained and whatever you try (adding gems and the like) will all be in your ```~/.tokaido``` directory. If you feel things have been messed with, you can always uninstall by running ```sudo sh /path/to/Tokaido.app/Contents/Resources/uninstall.sh```

But the solution is known, you need a way to have the GEM_PATH and GEM_HOME environments set.

**Comment by jamesrward** [comment]
OK.  Not solved yet but I think I'm on the right path.  [This workaround](http://ruby-on-rails.wikidot.com/rubyminelocalbundlepathbug) for a bundler config issue gives me hope that I can fix this with a single terminal command.  I tried this but still no luck:
```bash
GEM_PATH="/Users/James/.tokaido/Gems/2.1.0/" GEM_HOME="/Users/James/.tokaido/Gems/2.1.0/" /Applications/RubyMine.app/Contents/MacOS/rubymine
```

**Comment by androbtech** [comment]
Downloading Rubymine now. Will report what I can find.

**Comment by androbtech** [comment]
Try adding to PATH the gems 'bin' directory, too:

```PATH="/Users/James/.tokaido/Gems/2.1.0/bin:$PATH"```

**Comment by jamesrward** [comment]
I just facepalmed after reading [this suggestion](http://stackoverflow.com/a/18542462/1763637) and loaded the terminal from inside Tokaido and opened Rubymine from there with:
```bash
open -a /Applications/RubyMine.app/
```
But echo $GEM_PATH from the terminal inside Rubymine shows that it has reverted to my global RVM gem path.  Looks like environment variables are overridden during Rubymine launch.  :(

**Comment by androbtech** [comment]
Rubymine makes the task quite difficult.

Create a '.gem' folder in your home directory. Basically:

```mkdir -p .gem/ruby``` and ```cd ~/.gem/ruby```

Symlink the gems ```ln -s ~/.tokaido/Gems/2.1.0 .``` and then try adding an SDK from 'Languages and Frameworks' in Rubymine.

**Comment by jamesrward** [comment]
Wow great sleuthing, works like a charm.  Thanks for all your assistance.  I'll close this down and try to make note if I hit any weirdness.

**Comment by androbtech** [comment]
In case you start using postgres, and this means installing the 'pg' gem. Ideally, you'd add the gem entry in your project's Gemfile followed by running the `bundle` command.

With Tokaido, you'd click 'Open in Terminal' so the environment variables are set properly and postgress's headers are set in the path appropiately.

This is no longer the case with the latest Postgres.app release. The bug is fixed but we haven't released yet.

In this case, you'd need 'Open in Terminal' and run

```gem install pg -- --with-pg-config=/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config```

Depending on the Postgres.app version you have installed, just replace the version and it should install the gem correctly.

Just a heads up.
