### ISSUE TITLE
subdomains

### ISSUE THREAD

**Issue by amHammock** [tokaido/tokaidoapp#82]
I'm using Tokaido 2.2 for a new Rails app.  Install and initial dev stages going well, now I need to add support for subdomains and can't get it working.  Adding a subdomain to the tokaido url (e.g. subdomain.myapp.tokaido) just hangs in the browser although I can ping any subdomain of myapp.tokaido from the terminal and get responses from 127.0.0.1.  

I tried installing pow and using subdomain.myapp.dev (with the app booted in Tokaido) but that hangs as well

I also tried modifying etc/hosts file and adding subdomain.myapp.tokaido to 127.0.0.1, and adding subdomain.myapp.com also (and trying various port numbers on the url (3000, 30405) to get it to route to the tokaido app instance.  No dice.

How can I implement subdomains with Tokaido?

**Comment by androbtech** [comment]
I found the bug. This happens within Tokaido's Muxr.

I'm not sure when we are doing a new release. However, I'd be more than happy to let you know what code to add into Tokaido to get subdomains working.
