### ISSUE TITLE
app bundles in Terminal, but Tokaido won't bundle it

### ISSUE THREAD

**Issue by jm3** [tokaido/tokaidoapp#83]
is it common that an app which bundles fine in the Terminal won't bundle in Tokaido?

![tokaido bundling](https://cloud.githubusercontent.com/assets/12213/8914571/f0994656-3454-11e5-9c5b-308e4dde2a21.jpg)

**Comment by androbtech** [comment]
Is your app bundling fine from the Terminal within Tokaido's Sandboxed Environment? That is, did you click 'Open In Terminal' and bundle'd the app from there?

Try also adding an app within Tokaido's UI and do not add more subdomains, that is, leave it as "140proof.tokaido" instead of "api.140proff.com.tokaido" and test it out.

Let me know.

**Comment by jm3** [comment]
yes, @androbtech, the app bundles fine within Tokaid's Sandboxed Environment:

```
export TOKAIDO_GEM_NAMESPACE=2.2.0
export TOKAIDO_PATH=/Users/jm3/.tokaido/Rubies/2.2.2-p95/bin
export TOKAIDO_APP_DIR=/Users/jm3
source /Users/jm3/Desktop/Tokaido.app/Contents/Resources/SetupTokaido.sh
Last login: Mon Jul 27 15:04:18 on ttys000
% export TOKAIDO_GEM_NAMESPACE=2.2.0
% export TOKAIDO_PATH=/Users/jm3/.tokaido/Rubies/2.2.2-p95/bin
% export TOKAIDO_APP_DIR=/Users/jm3
% source /Users/jm3/Desktop/Tokaido.app/Contents/Resources/SetupTokaido.sh
% cd app
% bundle
Using rake 10.1.1
...
Using zencoder 2.5.0
Updating files in vendor/cache
Your bundle is complete!
Use bundle show [gemname] to see where a bundled gem is installed.
%
```

> Try also adding an app within Tokaido's UI and do not add more subdomains, that is, leave it as "140proof.tokaido" instead of "api.140proff.com.tokaido" and test it out.

I did add the app using Tokaido's GUI; api.140proof.com is the name of the repo. I tried renaming the app to simply `api` / `api.tokaido` but Tokaido's GUI gives the same bundle error:

![tokaido](https://cloud.githubusercontent.com/assets/12213/8941990/df6322e8-3527-11e5-9f87-2b33648b7a61.png)

Let me know if there's some additional instructions or system check I should be running.

**Comment by androbtech** [comment]
Thanks @jm3 

Please try ```bundle exec rails server``` in the terminal and let me know if it runs.

Please post what's inside the files ```bootstrap.err, bootstrap.out, firewall.err, and firewall.out``` as well as your ```app.tokaido.out``` files so I can try to investigate.
