### ISSUE TITLE
cant "open Tokaido.xcworkspace"

### ISSUE THREAD

**Issue by dfarfan85** [tokaido/tokaidoapp#84]
Hi i followed all instructions from the README:

> When first cloning this repo, be sure to run the following:
> 
> ```
> gem install cocoapods
> pod install
> Scripts/package.sh
> open Tokaido.xcworkspace
> ```
> 
> You should then be able to build and run Tokaido in Xcode.

I was able to do all of these except the last one that is `open Tokaido.xcworkspace`. The only thing in the repo folder i found close was `Toakaido.xcodeproj`. 

I am new to dev and don't really understand what this is supposed to do. Everything else looks to be running fine and I even created a test myapp and got up my server and local:3000 which was successful. I was also able to manage it from the Toakaido manage apps feature that is GUI and on the terminal.

I also ran a rake -T and everything went good.

Also after i ran `Scripts/package,sh` it said that I should run `make test`.

However I got this when I tried it:

`Davids-MacBook-Pro:tokaidoapp David$ make test
make: *** No rule to make target`test'.  Stop.`

Could somebody help me with this?

**Comment by andrasio** [comment]
Sorry about that. 

Please download again the repo and try it out in development mode.
