### ISSUE TITLE
Uninstall script tries to remove /usr/include/ files

### ISSUE THREAD

**Issue by paolovalladolid** [tokaido/tokaidoapp#86]
I don't think uninstall.sh should be trying to remove these files:

rm /usr/include/iconv.h
rm /usr/include/libcharset.h
rm /usr/include/localcharset.h

The script was stopped by permissions.  They are dated more than a year before I installed Tokaido

**Comment by andrasio** [comment]
Sorry about that. The strategy was changed (these were there for avoiding Nokogiri installation failures back in the day since the gem looked at those hard-coded paths). 

Tokaido installed those files. It's gone now though. Check our latest release and thank you for reporting this.
