### ISSUE TITLE
Tokaido sync issue

### ISSUE THREAD

**Issue by matthewdonker** [tokaido/tokaidoapp#87]
Created a test.txt file in docroot and it's not available in the browser or in the nginx container. Changes to existing files are not reflected either.

Tokaido version: v1.7.1
macOS: 10.14.4

**Comment by andrasio** [comment]
Not sure what are you looking to do. Can you be more specific? Tokaido manages an app if you choose to, you add it through the UI and boot from there using the name given to the app.

**Comment by andrasio** [comment]
Closing this for now.
